apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boundary-ingress
  namespace: aniket-test
spec:
  ingressClassName: nginx
  rules:
  - host: staging-keyclock.cladbe.com-1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: boundary
            port:
              number: 9200
